### ISSUE TITLE
Provide light style

### ISSUE THREAD

**Issue by bremensaki** [kra-mo/sly#23]
Installed via Flathub, the application is starting up in dark mode despite my GNOME system theme being set to light. I can't see any control to change this, but I may be missing it as I cannot focus properly on the UI elements. 

This is an accessibility issue, the system theme should be used by default.

**Comment by kra-mo** [comment]
The system theme will not be used by default, many media-related applications are dark by default for a reason, to let the user focus on the content. However, when an explicit light style is set, following that would be good.

**Comment by bremensaki** [comment]
If there's a reason to not follow the system theme in the absence of a defined preference, it's not a good one. Some of us literally cannot read text in dark themes, making navigating the UI very difficult, if not impossible.

I have my system theme set to light because I need it that way to be able to use the computer. Have a separate preference that overrides the system one for an application by all means, but it needs to default to the global preference or the settings themselves can be inaccessible.

**Comment by kra-mo** [comment]
The default global preference ('system') is not 'prefer light' though. It is 'no preference'. If you set your system to prefer light, it should follow it, otherwise, it can decide. This is not a matter of debate, it's just how the specification is written.

https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Settings.html
